In [2]:
import numpy as np

STARTING NUMPY

In [3]:
a= np.array([20,40,30])
b= np.array([4])
print(a*b)

[ 80 160 120]


CREATING ARRAY

In [4]:
arr= np.array([10,20,30,40])
print (type(arr))
print(arr[2:])

<class 'numpy.ndarray'>
[30 40]


INSPECTION OF DATA

In [5]:
arr= np.array([[10,20,30],[30,50,40]])
print(arr[1,2])
print(np.shape(arr))# dimension
print(np.size(arr))# size 
print(np.ndim(arr)) #no of rows
print(arr.dtype) # datatypes
print(arr.astype(float)) # changes datatype

40
(2, 3)
6
2
int32
[[10. 20. 30.]
 [30. 50. 40.]]


MATHEMATICAL OPERATIONS

In [6]:
a= np.array([10,20,30,80])
b=np.array([30,50,40,10])
print(a+b) # summation
print(np.add(a,b))# add function
'''same for substaraction, multiplication and division'''
print(np.sqrt(b).astype)

[40 70 70 90]
[40 70 70 90]
<built-in method astype of numpy.ndarray object at 0x0000027C7F2766D0>


JOINING AARAY

In [7]:
a= np.array([10,20,30,80])
b=np.array([30,50,40,10])
print(np.concatenate([a,b]))# concatenate
c= np.array([[10,20,30],[30,50,40]])
d=np.array([[10,20,30],[30,50,40]])
print(np.concatenate([c,d],axis=0))# concatenate the verticall 
print(np.concatenate([c,d],axis=1))# concatenate at horizontally
print(np.hstack([c,d]))# concatenate at horizontally
print(np.vstack([c,d]))# concatenate the vertically

[10 20 30 80 30 50 40 10]
[[10 20 30]
 [30 50 40]
 [10 20 30]
 [30 50 40]]
[[10 20 30 10 20 30]
 [30 50 40 30 50 40]]
[[10 20 30 10 20 30]
 [30 50 40 30 50 40]]
[[10 20 30]
 [30 50 40]
 [10 20 30]
 [30 50 40]]


SPLITTING ARRAY

In [8]:
 
a= np.array([10,20,30,80,90,60])
print(np.array_split(a,2))# splits array according to the parameter number

[array([10, 20, 30]), array([80, 90, 60])]


ADD AND REMOVE ARRAY

In [9]:
 
a= np.array([10,20,30,80,90,60])
print(np.append(a,[90,100]))# appends value or array at back
print(np.insert(a,1,60))# 1: array name 2: index 3:value
print(np.insert(a,[1,3],[40])) #insert number at two different index
c= np.array([[10,20,30],[30,50,40]])
print(np.insert(c,[1,2],[40])) # insert value after converting into 1d array
print(np.insert(c,[1,2],[40], axis=0))#insert an array of parameter value
print(np.delete(a,1))# delete value at given index
print(np.delete(c,1))# delete value after converting into 1d array
print(np.delete(c,1, axis=1))# delete value at given index in each row in matrix

[ 10  20  30  80  90  60  90 100]
[10 60 20 30 80 90 60]
[10 40 20 30 40 80 90 60]
[10 40 20 40 30 30 50 40]
[[10 20 30]
 [40 40 40]
 [30 50 40]
 [40 40 40]]
[10 30 80 90 60]
[10 30 30 50 40]
[[10 30]
 [30 40]]


SORT

In [10]:
 
a= np.array([10,30,20,80,90,60])
print(np.sort(a))# sort function
c= np.array([[10,20,30],[30,50,40]])
print(np.sort(c))# sort all rows in matrix

[10 20 30 60 80 90]
[[10 20 30]
 [30 40 50]]


SEARCH

In [11]:
 
a= np.array([10,30,20,80,90,60])
s=np.where(a%20==0)# gives the index of condition in where
print(s)
e=np.sort(a)
print(np.searchsorted(e,3))#Works on sorted array

(array([2, 3, 5], dtype=int64),)
0


FILTER

In [12]:
 
a= np.array([10,30,20,80])
f=[True,False, True, False]
new=a[f]# prints values of a where index of f = true
print(new)
g=a>25 #gives an bool array which satisfies the conditions
print(g)
print(a[g])

[10 20]
[False  True False  True]
[30 80]


AGGREGATE


In [13]:
 
a= np.array([10,30,20,80])
print(np.sum(a))#sum
print(np.min(a))#minimum value
print(np.max(a))#maximum value
print(np.size(a))#size of array
print(np.cumsum(a))#cumulative product
print(np.cumprod(a))#cumulative product

140
10
80
4
[ 10  40  60 140]
[    10    300   6000 480000]


STATISTICS

In [14]:
 
import statistics as stat
a= np.array([10,30,20,80])
print(np.mean(a))# mean of array
print(np.median(a))# median of array
print(stat.mode(a))# mode of array
print(np.std(a))# standard deviation of array
print(np.var(a))# variance of array
print(np.corrcoef(a))# correlation coefficient of array

35.0
25.0
10
26.92582403567252
725.0
1.0


random numbers

In [15]:
d=0
for j in range(100):
    a=np.random.randint(0,30,12)
    b=np.random.randint(40,90,190)
    c=np.random.randint(90,100,20)
    e=np.concatenate([a,b,c])
    d+=np.percentile(e,5)
d/100

27.88900000000001